# Build dev image
FROM {{ BUILDIMAGE }} as builder

# prepare project
WORKDIR /app

# prepare system for private repo
RUN git config --global url."https://{{ GITLAB_USER }}:{{ GITLAB_ACCESS_TOKEN }}@git.vunder.dev/".insteadOf "https://git.vunder.dev/"
ENV CARGO_TARGET_DIR=/tmp/{{ PROJECT_NAME }}/target

CMD ["make", "run-{{ CMD_NAME }}"]

