# Build dev image
FROM rust:1.54-buster as builder

# prepare project
WORKDIR /app

# prepare system for private repo
RUN git config --global url."https://sveatlo:Hk2sjmfywv4yHuQyLehB@git.vunder.dev/".insteadOf "https://git.vunder.dev/"
ENV CARGO_TARGET_DIR=/tmp/vetmanager-backend/target

CMD ["make", "run-api"]

